"""
DatabaseStack: RDS PostgreSQL 15 in a private VPC subnet with credentials
stored in AWS Secrets Manager.
"""
from __future__ import annotations

import aws_cdk as cdk
from aws_cdk import (
    Stack,
    aws_ec2 as ec2,
    aws_rds as rds,
    aws_secretsmanager as secretsmanager,
)
from constructs import Construct


class DatabaseStack(Stack):
    """
    Creates:
      - A VPC with isolated private subnets (no NAT gateway required for the DB).
      - A security group that allows inbound PostgreSQL traffic (port 5432) from
        within the VPC CIDR.
      - An RDS PostgreSQL 15 instance placed in the isolated subnet group.
      - A Secrets Manager secret automatically generated by the RDS construct.

    Properties exposed for other stacks:
      - ``vpc``      – the VPC containing the database.
      - ``instance`` – the RDS DatabaseInstance.
      - ``secret``   – the Secrets Manager secret holding the DB credentials.
    """

    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # ------------------------------------------------------------------ #
        # VPC — isolated private subnets only (no NAT gateway, no IGW)       #
        # ------------------------------------------------------------------ #
        self._vpc = ec2.Vpc(
            self,
            "Vpc",
            ip_addresses=ec2.IpAddresses.cidr("10.0.0.0/16"),
            max_azs=2,
            # Isolated subnets have no route to the internet — perfect for a DB.
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="Isolated",
                    subnet_type=ec2.SubnetType.PRIVATE_ISOLATED,
                    cidr_mask=24,
                )
            ],
            # No NAT gateways needed when every subnet is fully isolated.
            nat_gateways=0,
        )

        # ------------------------------------------------------------------ #
        # Security group — allow port 5432 from within the VPC               #
        # ------------------------------------------------------------------ #
        self._db_sg = ec2.SecurityGroup(
            self,
            "DbSecurityGroup",
            vpc=self._vpc,
            description="Allow PostgreSQL access from within the VPC",
            allow_all_outbound=False,
        )

        self._db_sg.add_ingress_rule(
            peer=ec2.Peer.ipv4(self._vpc.vpc_cidr_block),
            connection=ec2.Port.tcp(5432),
            description="PostgreSQL from VPC CIDR",
        )

        # ------------------------------------------------------------------ #
        # RDS PostgreSQL 15 instance                                          #
        # ------------------------------------------------------------------ #
        # multi_az defaults to False (staging); callers can override via CDK
        # context or by subclassing / composing this stack for prod.
        multi_az: bool = self.node.try_get_context("multiAz") or False

        self._instance = rds.DatabaseInstance(
            self,
            "PostgresInstance",
            engine=rds.DatabaseInstanceEngine.postgres(
                version=rds.PostgresEngineVersion.VER_15
            ),
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.BURSTABLE4_GRAVITON,
                ec2.InstanceSize.MICRO,
            ),
            vpc=self._vpc,
            vpc_subnets=ec2.SubnetSelection(
                subnet_type=ec2.SubnetType.PRIVATE_ISOLATED
            ),
            security_groups=[self._db_sg],
            multi_az=multi_az,
            # RDS auto-generates a Secrets Manager secret when credentials are
            # not provided explicitly — we rely on that behaviour.
            credentials=rds.Credentials.from_generated_secret(
                username="recipemate_admin",
                secret_name=f"{self.stack_name}/db-credentials",
            ),
            database_name="recipemate",
            # Keep storage minimal for staging; encryption at rest is on by default.
            allocated_storage=20,
            storage_type=rds.StorageType.GP2,
            deletion_protection=False,
            # Staging-friendly: tear the instance down with the stack. Override
            # for prod via context/removal-policy hint. (There is no
            # ``remove_on_delete`` prop; ``removal_policy`` is the real knob.)
            removal_policy=cdk.RemovalPolicy.DESTROY,
            # Automatic minor version upgrades keep the instance patched.
            auto_minor_version_upgrade=True,
            backup_retention=cdk.Duration.days(7),
        )

        # ------------------------------------------------------------------ #
        # Outputs                                                             #
        # ------------------------------------------------------------------ #
        cdk.CfnOutput(
            self,
            "DbEndpoint",
            value=self._instance.db_instance_endpoint_address,
            description="RDS PostgreSQL endpoint hostname",
        )

        cdk.CfnOutput(
            self,
            "DbSecretArn",
            value=self._instance.secret.secret_arn,  # type: ignore[union-attr]
            description="ARN of the Secrets Manager secret holding DB credentials",
        )

    # ---------------------------------------------------------------------- #
    # Public properties                                                       #
    # ---------------------------------------------------------------------- #

    @property
    def vpc(self) -> ec2.Vpc:
        """The VPC that contains the database."""
        return self._vpc

    @property
    def instance(self) -> rds.DatabaseInstance:
        """The RDS PostgreSQL instance."""
        return self._instance

    @property
    def secret(self) -> secretsmanager.ISecret:
        """
        The Secrets Manager secret holding the auto-generated DB credentials.
        The secret JSON contains keys: ``username``, ``password``, ``host``,
        ``port``, ``dbname``, and ``engine``.
        """
        # rds.DatabaseInstance.secret is non-None when credentials are
        # generated automatically; assert here to surface any misconfiguration.
        assert self._instance.secret is not None, (
            "RDS secret is None — credentials were not auto-generated."
        )
        return self._instance.secret
