"""
SecretsStack: centralises AWS Secrets Manager secrets for RecipeMate.

The only application secret that is not already managed by another stack is the
OpenAI API key (the database credentials secret is generated by the RDS
construct inside ``DatabaseStack``). This stack provisions that OpenAI secret
with a *stable, predictable name* so other stacks can look it up by reference,
and so an operator can populate its value out of band.

Crucially, the secret's value is **never** placed in the CloudFormation
template. ``Secret`` is created with a generated placeholder; the real key is
set after deploy via the AWS CLI or console, e.g.::

    aws secretsmanager put-secret-value \\
        --secret-id recipemate/<env>/openai-api-key \\
        --secret-string '{"OPENAI_API_KEY":"sk-..."}'

Consumers (QueueStack, ApiStack) receive the ``ISecret`` and grant their roles
read access, so the value is fetched at runtime rather than embedded at synth
time.
"""
from __future__ import annotations

import aws_cdk as cdk
from aws_cdk import (
    Stack,
    aws_secretsmanager as secretsmanager,
)
from constructs import Construct


class SecretsStack(Stack):
    """
    Creates:
      - A Secrets Manager secret for the OpenAI API key, named
        ``recipemate/<env>/openai-api-key``. The secret is seeded with a
        generated placeholder so no sensitive value ever lands in the template;
        the real key is written post-deploy.
      - A Secrets Manager secret for the Flask ``SECRET_KEY``, named
        ``recipemate/<env>/flask-secret-key``. Unlike the OpenAI key, this
        secret's value is *generated by Secrets Manager and used as-is*: a
        random signing key IS the real value, so there is **no** post-deploy
        overwrite step (the OpenAI secret's generated value is only a
        placeholder for a key an operator supplies out of band).

    Properties exposed for other stacks:
      - ``openai_secret``      – the OpenAI API key :class:`ISecret`.
      - ``openai_secret_name`` – the stable secret name, for reference lookups.
      - ``flask_secret``       – the Flask ``SECRET_KEY`` :class:`ISecret`.
      - ``flask_secret_name``  – the stable secret name, for reference lookups.
    """

    #: JSON key under which the OpenAI API key is stored inside the secret.
    OPENAI_SECRET_JSON_KEY: str = "OPENAI_API_KEY"

    #: JSON key under which the Flask signing key is stored inside the secret.
    FLASK_SECRET_JSON_KEY: str = "SECRET_KEY"

    def __init__(
        self,
        scope: Construct,
        id: str,
        *,
        env_name: str = "staging",
        **kwargs,
    ) -> None:
        super().__init__(scope, id, **kwargs)

        self._openai_secret_name = f"recipemate/{env_name}/openai-api-key"

        # The secret is created with a generated placeholder value so the real
        # OpenAI key is never rendered into the CloudFormation template. The
        # ``secret_string_template`` fixes the JSON shape; ``generate_string_key``
        # fills in a random placeholder for OPENAI_SECRET_JSON_KEY that an
        # operator overwrites post-deploy with ``put-secret-value``.
        self._openai_secret = secretsmanager.Secret(
            self,
            "OpenAiApiKeySecret",
            secret_name=self._openai_secret_name,
            description="OpenAI API key used for recipe extraction and LLM search",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template="{}",
                generate_string_key=self.OPENAI_SECRET_JSON_KEY,
                # Exclude characters that complicate shell/JSON handling of the
                # placeholder. The real key replaces this value anyway.
                exclude_punctuation=True,
                password_length=40,
            ),
            # Secrets should survive a stack teardown so a value populated out
            # of band is not silently destroyed. Override for throwaway envs.
            removal_policy=cdk.RemovalPolicy.RETAIN,
        )

        self._flask_secret_name = f"recipemate/{env_name}/flask-secret-key"

        # The Flask SECRET_KEY is created WITHOUT any real value in the
        # template; Secrets Manager generates a strong random value and that
        # generated value is the one the app uses. A signing key does not come
        # from an operator — a cryptographically random string IS the real
        # value — so, unlike the OpenAI secret, there is no post-deploy
        # ``put-secret-value`` step. ``exclude_punctuation`` keeps the value
        # shell/JSON-safe; a 64-char length gives ample signing entropy.
        self._flask_secret = secretsmanager.Secret(
            self,
            "FlaskSecretKey",
            secret_name=self._flask_secret_name,
            description="Flask SECRET_KEY used for session/CSRF signing",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template="{}",
                generate_string_key=self.FLASK_SECRET_JSON_KEY,
                exclude_punctuation=True,
                password_length=64,
            ),
            # Keep the signing key stable across deploys: regenerating it would
            # invalidate every live session/CSRF token. Override for throwaway
            # envs.
            removal_policy=cdk.RemovalPolicy.RETAIN,
        )

        # ------------------------------------------------------------------ #
        # Outputs                                                             #
        # ------------------------------------------------------------------ #
        cdk.CfnOutput(
            self,
            "OpenAiSecretName",
            value=self._openai_secret_name,
            description="Secrets Manager name holding the OpenAI API key",
        )
        cdk.CfnOutput(
            self,
            "OpenAiSecretArn",
            value=self._openai_secret.secret_arn,
            description="ARN of the OpenAI API key secret",
        )
        cdk.CfnOutput(
            self,
            "FlaskSecretKeyName",
            value=self._flask_secret_name,
            description="Secrets Manager name holding the Flask SECRET_KEY",
        )
        cdk.CfnOutput(
            self,
            "FlaskSecretKeyArn",
            value=self._flask_secret.secret_arn,
            description="ARN of the Flask SECRET_KEY secret",
        )

    # ---------------------------------------------------------------------- #
    # Public properties                                                       #
    # ---------------------------------------------------------------------- #

    @property
    def openai_secret(self) -> secretsmanager.ISecret:
        """The Secrets Manager secret holding the OpenAI API key."""
        return self._openai_secret

    @property
    def openai_secret_name(self) -> str:
        """The stable name of the OpenAI API key secret."""
        return self._openai_secret_name

    @property
    def flask_secret(self) -> secretsmanager.ISecret:
        """The Secrets Manager secret holding the Flask ``SECRET_KEY``."""
        return self._flask_secret

    @property
    def flask_secret_name(self) -> str:
        """The stable name of the Flask ``SECRET_KEY`` secret."""
        return self._flask_secret_name
